# Numpy Docs - Day 1

In [5]:
import numpy as np

In [24]:
# a = np.array([[1., 0., 0.],
#             [0., 1.,2.]])

a = np.arange(12).reshape(4,3)

In [25]:
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [26]:
a.ndim

2

In [27]:
a.shape

(4, 3)

In [28]:
a.size

12

In [29]:
a.dtype

dtype('int32')

In [31]:
# item size is size in bytes for each element of the array.(int dtype has y bytes)
a.itemsize

4

In [32]:
# data is buffer containing the actual elements of the array.
a.data

### Creating array

In [37]:
b = np.array([1., 2., 3.])
print(b)
b.dtype

[1. 2. 3.]


dtype('float64')

In [41]:
# complex number array
c = np.array([[7, 6], [5, 9]], dtype="complex")
c

array([[7.+0.j, 6.+0.j],
       [5.+0.j, 9.+0.j]])

In [42]:
# Quick array generating functions
# 1. Zeros

o = np.zeros((2, 4))
o

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
# 2. ones
l = np.ones((2, 5, 3))
print(l)
l.ndim

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


3

In [48]:
# 3. empty

np.empty((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [51]:
# Arange function to create range based array

arg = np.arange(5, 50, 5)
arg

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [53]:
# arange for float array
arg = np.arange(5, 10, 0.5)
arg

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [62]:
#  linspace returns the number of elements that we want evenly distributed of given numbers, instead of the step unlike arange

ls = np.linspace(0, 10, 9)
ls

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [63]:
# Reshaping array

np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [66]:
np.arange(10000).reshape(500, 20)

array([[   0,    1,    2, ...,   17,   18,   19],
       [  20,   21,   22, ...,   37,   38,   39],
       [  40,   41,   42, ...,   57,   58,   59],
       ...,
       [9940, 9941, 9942, ..., 9957, 9958, 9959],
       [9960, 9961, 9962, ..., 9977, 9978, 9979],
       [9980, 9981, 9982, ..., 9997, 9998, 9999]])

NumPy automatically skips the central part of the array and only prints the corners,
To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported


### Basic Operators in numpy

In [67]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [68]:
c = a - b
c

array([20, 29, 38, 47])

In [69]:
b ** 2

array([0, 1, 4, 9])

In [73]:
np.sin(a) * 10

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [74]:
a < 35

array([ True,  True, False, False])

In [75]:
A = np.array([[1, 1],
             [0, 1]])
B = np.array([[2, 0],
             [3, 4]])

A * B

array([[2, 0],
       [0, 4]])

In [78]:
A @ B # (Matrix multiplication)

array([[5, 4],
       [3, 4]])

In [81]:
A.dot(B) # Matrix Product

array([[5, 4],
       [3, 4]])

In [84]:
rng = np.random.default_rng(1) # create instance of default random number generator
rng

Generator(PCG64) at 0x2249E52ADC0

In [89]:
a = np.ones((2, 3), dtype = int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [90]:
b = rng.random((2, 3))
b

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [91]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [92]:
b += a
b

array([[3.82770259, 3.40919914, 3.54959369],
       [3.02755911, 3.75351311, 3.53814331]])

In [93]:
a += b # b is not automatically converted to integer type

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [96]:
a = np.ones(3, dtype=np.int32)
a

array([1, 1, 1])

In [100]:
b = np.linspace(0, np.pi, 3)
print(b)
print(b.dtype.name)

[0.         1.57079633 3.14159265]
float64


In [103]:
c = a + b
print(c)
print(c.dtype.name)

[1.         2.57079633 4.14159265]
float64


In [105]:
d = np.exp(c * 1j)
print(d)
print(d.dtype.name)

[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [106]:
arr = rng.random((2, 3))
arr

array([[0.32973172, 0.7884287 , 0.30319483],
       [0.45349789, 0.1340417 , 0.40311299]])

In [108]:
print(arr.sum())
print(arr. min())
print(arr.max())

2.412007822394087
0.13404169724716475
0.7884287034284043


In [109]:
g = np.arange(18). reshape(3, 6)
g

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [110]:
g.sum(axis = 0) # sum of each cols


array([18, 21, 24, 27, 30, 33])

In [111]:
g.sum(axis = 1) # sum of each rows

array([15, 51, 87])

In [112]:
g.cumsum(axis = 1) # cumulative sum of each elements based on rows

array([[ 0,  1,  3,  6, 10, 15],
       [ 6, 13, 21, 30, 40, 51],
       [12, 25, 39, 54, 70, 87]])

# Universal Functions

In [113]:
h = np.arange(3)
h

array([0, 1, 2])

In [114]:
np.exp(h)

array([1.        , 2.71828183, 7.3890561 ])

In [115]:
np.sqrt(h)

array([0.        , 1.        , 1.41421356])

In [122]:
i = np.array([2, -2, 3.78547])

In [123]:
np.add(h, i)

array([ 2.     , -1.     ,  5.78547])