## Splitting one array into several smaller ones

In [2]:
import numpy as np

In [4]:
rgn = np.random.default_rng(1)

In [5]:
a = np.floor(10 * rgn.random((2, 12)))
a

array([[5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.]])

In [6]:
np.hsplit(a,3) # Splits a into 3

[array([[5., 9., 1., 9.],
        [3., 7., 3., 4.]]),
 array([[3., 4., 8., 4.],
        [1., 4., 2., 2.]]),
 array([[5., 0., 7., 5.],
        [7., 2., 4., 9.]])]

In [7]:
np.hsplit(a,(3, 4)) # Splits a after the third and the fourth column

[array([[5., 9., 1.],
        [3., 7., 3.]]),
 array([[9.],
        [4.]]),
 array([[3., 4., 8., 4., 5., 0., 7., 5.],
        [1., 4., 2., 2., 7., 2., 4., 9.]])]

## Copies and views

In [9]:
# No copy at all

a = np.array([[0, 1, 2, 3],
             [4, 5, 6, 7],
             [8, 9, 10, 11]])
b = a # new object is not created
b is a # a and b are 2 name for same ndarray obj

True

In [10]:
def f(x):
    print(id(x))
    
id(a)

1490449578768

In [11]:
f(a)

1490449578768


In [13]:
## View or shallow copy

c = a.view()
c is a

False

In [15]:
c.base is a # c is a view of the data owned by a

True

In [17]:
c = c.reshape((2, 6))  # a's shape doesn't change
a.shape

(3, 4)

In [18]:
c[0, 4] = 1234         # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [19]:
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [20]:
## Deep copy

d = a.copy()
d is a

False

In [21]:
d.base is a

False

In [23]:
d[0, 0] = 9999
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [30]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a

In [31]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Advanced indexing and index tricks

#### Indexing with arrays of indices

In [35]:
a = np.arange(12) ** 2
i = np.array([1, 1, 3, 8, 5])
a[i]  # elements in a at position i

array([ 1,  1,  9, 64, 25])

In [37]:
palatte = np.array([[0, 0, 0], #black
                   [255, 0, 0], #red
                   [0, 255, 0], # green
                   [0, 0, 255], # blue
                   [255, 255, 255]]) # ehite

image = np.array([[0, 1,2, 0], 
                 [0, 3, 4, 0]])

palatte[image] # array of palatte at position image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [38]:
# We can also give indexes for more than one dimension.
# The arrays of indices for each dimension must have the same shape.

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
i = np.array([[0, 1],
             [1, 2]])
j = np.array([[2, 1],
             [3, 3]])
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [40]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [41]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [43]:
## Another common use of indexing with arrays is the search of the maximum
# value of time-dependent series:

time = np.linspace(20, 145, 5)
data = np.sin(np.arange(20)).reshape(5, 4)
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [44]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [46]:
ind = data.argmax(axis=0) # index of the maxima for each series
ind

array([2, 0, 3, 1], dtype=int64)

In [48]:
time_max = time[ind]

data_max = data[ind, range(data.shape[1])]
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [49]:
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [50]:
np.all(data_max == data.max(axis=0))

True

In [51]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [52]:
a[[1, 3, 4]] = 0
a

array([0, 0, 2, 0, 0])

In [53]:
a = np.arange(5)
a[[0, 0, 2]] += 1
a

array([1, 1, 3, 3, 4])